# Generated by Django 5.2.13 on 2026-05-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_status_order_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
    ]


