# Generated by Django 5.2.13 on 2026-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_order_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Nhân viên'), ('customer', 'Khách hàng')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]


