# Generated by Django 5.2.13 on 2026-05-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wishlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('VNPAY', 'VNPay')], default='COD', max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thanh toán thành công'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=20)),
                ('txn_ref', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.order')),
            ],
        ),
    ]


