# Generated by Django 5.2.13 on 2026-05-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_nxb_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('favorite', models.BooleanField(default=False)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('nxb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nxb')),
            ],
        ),
    ]
