# Generated by Django 5.2.13 on 2026-05-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nxb',
        ),
        migrations.DeleteModel(
            name='NXB',
        ),
    ]
