# Generated by Django 5.2.13 on 2026-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_nxb_delete_nxb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
